name:                hexml-lens
version:             0.2.0
synopsis:            Lenses for the hexml package
description:         Lenses for the hexml package
homepage:            https://github.com/pepeiborra/hexml-lens#readme
license:             BSD3
author:              Jose Iborra
maintainer:          pepeiborra@gmail.com
copyright:           All Rights Reserved
category:            lens
extra-source-files:
- README.md

library: 
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - bytestring
    - contravariant
    - foundation
    - hexml
    - lens
    - profunctors
    - text

tests:
  courses:
    source-dirs: examples
    main: courses.hs
    dependencies:
      - base
      - bytestring
      - hexml
      - hexml-lens
      - hspec
      - lens
      - wreq
  doctests:
    main: Doctests.hs
    source-dirs:
      - test
    dependencies:
      - base
      - doctest
      - hexml-lens
      - QuickCheck
